import { changeDateFormat } from "../src/features/users/User";

// dates are generated by mongoDB so should exist
// changeDateFormat converts them from "2023-03-18T20:06:37.926Z" to "18/03/2023"
// local is en-GB

test("changeDateFormat returns string", () => {
  const date = changeDateFormat("2023-03-18T20:06:37.926Z");
  expect(typeof date).toBe("string");
});

test("changeDateFormat returns a date in dd/mm/yyyy format", () => {
  const date = changeDateFormat("2023-03-18T20:06:37.926Z");
  expect(date).toBe("18/03/2023");
});